# Generated by Django 3.0.2 on 2020-01-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_text',
            field=models.TextField(blank=True, max_length=512, verbose_name='preview text'),
        ),
    ]
